# Generated by Django 6.0.1 on 2026-01-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Psychologist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Ünvan')),
                ('short_bio', models.TextField(blank=True, verbose_name='Kısa Tanıtım (Özet)')),
                ('about_preview', models.TextField(blank=True, verbose_name='Birkaç Kelime ile (Kısa)')),
                ('about_full', models.TextField(blank=True, verbose_name='Ayrıntılı Özgeçmiş (Uzun)')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='psychologists/profile/', verbose_name='Profil Fotoğrafı')),
                ('is_online', models.BooleanField(default=True, verbose_name='Online Görüşme Var')),
                ('is_in_person', models.BooleanField(default=True, verbose_name='Yüz Yüze Görüşme Var')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('city', models.CharField(blank=True, max_length=60, verbose_name='Şehir')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Sıralama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
            ],
            options={
                'verbose_name': 'Psikolog',
                'verbose_name_plural': 'Psikologlar',
                'ordering': ['order', 'full_name'],
            },
        ),
    ]
