# Generated by Django 6.0.1 on 2026-01-24 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Görsel')),
                ('category', models.CharField(choices=[('certificate', 'Sertifika'), ('office', 'Ofis'), ('event', 'Etkinlik'), ('other', 'Diğer')], default='other', max_length=20, verbose_name='Kategori')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='pages.psychologist', verbose_name='Psikolog')),
            ],
            options={
                'verbose_name': 'Galeri Görseli',
                'verbose_name_plural': 'Galeri Görselleri',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
