# Generated by Django 5.2.6 on 2026-01-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_education_alter_galleryimage_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Eğitimler ve Sertfikalar', 'verbose_name_plural': 'Eğitim ve Sertfika'},
        ),
        migrations.RemoveField(
            model_name='education',
            name='university_name',
        ),
        migrations.AddField(
            model_name='education',
            name='education',
            field=models.CharField(default='Bilinmiyor', max_length=100, verbose_name='Eğitimler ve Sertfikalar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='title',
            field=models.CharField(default='Bilinmiyor', verbose_name='Başlık'),
            preserve_default=False,
        ),
    ]
