# Generated by Django 5.2.6 on 2026-01-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_education_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, verbose_name='Çalışma Alanı')),
                ('definition', models.CharField(blank=True, verbose_name='Tanım')),
            ],
            options={
                'verbose_name': 'Calışma Alanları',
                'verbose_name_plural': 'Çalışma Alanı',
            },
        ),
        migrations.AlterField(
            model_name='education',
            name='education',
            field=models.CharField(max_length=100, null=True, verbose_name='Eğitimler ve Sertfikalar'),
        ),
        migrations.AlterField(
            model_name='education',
            name='title',
            field=models.CharField(null=True, verbose_name='Başlık'),
        ),
    ]
