# Generated by Django 6.0.1 on 2026-01-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_education_id_alter_galleryimage_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Pazartesi'), (1, 'Salı'), (2, 'Çarşamba'), (3, 'Perşembe'), (4, 'Cuma'), (5, 'Cumartesi'), (6, 'Pazar')], verbose_name='Gün')),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name='Açılış saati')),
                ('close_time', models.TimeField(blank=True, null=True, verbose_name='Kapanış saati')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Kapalı')),
            ],
            options={
                'verbose_name': 'Çalışma Saatleri',
                'verbose_name_plural': 'Çalışma Saati',
                'ordering': ['day'],
                'constraints': [models.UniqueConstraint(fields=('day',), name='unique_working_day')],
            },
        ),
    ]
